#!/bin/bash
# Hook: 30_update_docs.sh
# Type: on-save
# Description: Automatically updates the main documentation (README.md) or a technical summary
#              whenever a core governance file (steering/ or specs/) is modified.
# Compliance: Enforces the principle of "Documentation is always synchronized with Architecture."

# --- Configuration ---
# Define the core governance files to watch
GOVERNANCE_FILES=(
    ".kiro/steering/philosophy.md"
    ".kiro/steering/security.md"
    ".kiro/steering/structure.md"
    ".kiro/specs/requirements.md"
)

# Define the output file (e.g., a technical summary in the docs folder)
OUTPUT_FILE="docs/TECHNICAL_SUMMARY.md"

# --- Execution ---
echo "--- Running Kiro On-Save Documentation Update (30_update_docs.sh) ---"

# Check if the docs directory exists, if not, create it
mkdir -p docs

# Simple simulation of documentation generation:
echo "# Technical Summary of Kiro Blueprint Governance" > "$OUTPUT_FILE"
echo "This file is automatically generated by the 30_update_docs.sh hook." >> "$OUTPUT_FILE"
echo "Compliance: Ensures documentation is always synchronized with the latest architectural decisions." >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "## Core Principles (philosophy.md)" >> "$OUTPUT_FILE"
cat .kiro/steering/philosophy.md >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "## Security Standards (security.md)" >> "$OUTPUT_FILE"
cat .kiro/steering/security.md >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

echo "Documentation summary updated in $OUTPUT_FILE."

exit 0
